version: "3"

services:
  web:
    container_name: "EpiTravel"
    build:
      context: ../../
      dockerfile: utils/docker/Dockerfile
    ports:
      - 80:80
      - 3030:3030
    volumes:
      - ../../:/var/html/www/
      - ./vhost.conf:/opt/docker/etc/httpd/vhost.conf
    environment:
      - WEB_DOCUMENT_ROOT=/var/html/www/public
      - WEB_DOCUMENT_INDEX=index.php
    extra_hosts:
      - "epitravel.vm:127.0.0.1"
      - "www.epitravel.vm:127.0.0.1"
    networks:
      - default
networks:
  default:
    external: true
    name: back_default
